# Schema for the configuration of the OpenID Connect plugin.
openid_connect.client.plugin.keycloak:
  type: mapping
  label: 'OpenID Connect Keycloak settings'
  mapping:
    debug:
      type: boolean
      label: 'Enable debug mode'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client secret'
    iss_allowed_domains:
      type: string
      label: 'Domains that are allowed to initiate SSO using ISS'
    keycloak_base:
      type: string
      label: 'Keycloak base URL'
    keycloak_realm:
      type: string
      label: 'Keycloak realm'
    kc_idp_hint:
      type: string
      label: 'The default identity provider hint'
    userinfo_update_email:
      type: boolean
      label: 'Update email address in user profile'
    keycloak_i18n:
      type: mapping
      label: 'Multi-language settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable multi-language support'
        mapping:
          type: sequence
          label: 'Language mapping'
          sequence:
            type: mapping
            mapping:
              langcode:
                type: string
                label: 'Drupal language code'
              target:
                type: string
                label: 'Keycloak language code'
    keycloak_groups:
      type: mapping
      mapping:
        enabled:
          type: boolean
          label: 'Enable automatic user role assignments'
        claim_name:
          type: string
          label: 'User groups token claim name'
        split_groups:
          type: boolean
          label: 'Split group paths'
        split_groups_limit:
          type: boolean
          label: 'Group path nesting limit'
        rules:
          type: sequence
          label: 'Roles mapping rules'
          sequence:
            type: mapping
            mapping:
              id:
                type: string
                label: 'ID'
              role:
                type: string
                label: 'Drupal role'
              action:
                type: string
                label: 'Action'
              operation:
                type: string
                label: 'Evaluation type'
              pattern:
                type: string
                label: 'Pattern'
              case_sensitive:
                type: boolean
                label: 'Case sensitive'
              weight:
                type: integer
                label: 'Weight'
              enabled:
                type: boolean
                label: 'enabled'
    keycloak_sso:
      type: boolean
      label: 'Replace Drupal login with Keycloak single sign-on'
    keycloak_sign_out:
      type: boolean
      label: 'Enable Drupal-initiated single sign-out'
    check_session:
      type: mapping
      label: 'Check session settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable Keycloak-initiated single sign-out'
        interval:
          type: integer
          label: 'Session check interval'
    keycloak_locale_param:
      type: string
      label: 'Locale parameter variable name'
