version: '3.8'
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupalroot
    volumes:
      - db_data:/var/lib/mysql

  drupal:
    image: drupal:11-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./drupal/web:/var/www/html
      - ./drupal/web/sites/default/files:/var/www/html/sites/default/files
    environment:
      # optional php settings
      PHP_MEMORY_LIMIT: 512M

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  db_data:
  keycloak_data:
